services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoBayernPortal\:
        resource: ../../
        exclude: ../../{ApiEntity,ContaoManager,Maintenance,Resources}
